// Constantes utilisées à la place des enums (SQLite ne les supporte pas nativement)

const ROLES = {
  PATIENT: 'PATIENT',
  MEDECIN: 'MEDECIN',
  RECEPTIONNISTE: 'RECEPTIONNISTE',
  PHARMACIEN: 'PHARMACIEN',
  ADMIN: 'ADMIN',
};

const STATUT_RDV = {
  EN_ATTENTE: 'EN_ATTENTE',
  CONFIRME: 'CONFIRME',
  ANNULE: 'ANNULE',
  TERMINE: 'TERMINE',
};

const TYPE_RDV = {
  PRESENTIEL: 'PRESENTIEL',
  TELECONSULTATION: 'TELECONSULTATION',
};

const STATUT_PASSAGE = {
  EN_ATTENTE: 'EN_ATTENTE',
  APPELE: 'APPELE',
  CONSULTE: 'CONSULTE',
  PARTI: 'PARTI',
};

const NIVEAU_URGENCE = {
  FAIBLE: 'FAIBLE',
  MODERE: 'MODERE',
  URGENT: 'URGENT',
  CRITIQUE: 'CRITIQUE',
};

const STATUT_LIT = {
  LIBRE: 'LIBRE',
  OCCUPE: 'OCCUPE',
  RESERVE: 'RESERVE',
  MAINTENANCE: 'MAINTENANCE',
};

const TYPE_CHAMBRE = {
  STANDARD: 'STANDARD',
  VIP: 'VIP',
  SOINS_INTENSIFS: 'SOINS_INTENSIFS',
  MATERNITE: 'MATERNITE',
};

const STATUT_HOSPITALISATION = {
  EN_COURS: 'EN_COURS',
  TERMINEE: 'TERMINEE',
  ANNULEE: 'ANNULEE',
};

const MODE_PAIEMENT = {
  ESPECES: 'ESPECES',
  MOBILE_MONEY: 'MOBILE_MONEY',
  ASSURANCE: 'ASSURANCE',
  CARTE: 'CARTE',
};

const OPERATEUR_MOBILE = {
  ORANGE_MONEY: 'ORANGE_MONEY',
  WAVE: 'WAVE',
  FREE_MONEY: 'FREE_MONEY',
};

const STATUT_TRANSACTION = {
  EN_ATTENTE: 'EN_ATTENTE',
  REUSSI: 'REUSSI',
  ECHOUE: 'ECHOUE',
};

const STATUT_PAIEMENT = {
  EN_ATTENTE: 'EN_ATTENTE',
  PAYE: 'PAYE',
  ANNULE: 'ANNULE',
};

const STATUT_NOTIFICATION = {
  PLANIFIE: 'PLANIFIE',
  ENVOYE: 'ENVOYE',
  ECHOUE: 'ECHOUE',
};

const CANAL_NOTIFICATION = {
  SMS: 'SMS',
  EMAIL: 'EMAIL',
  PUSH: 'PUSH',
  IN_APP: 'IN_APP',
};

const LANGUE = {
  FR: 'FR',
  WO: 'WO',
};

const THEME = {
  CLAIR: 'CLAIR',
  SOMBRE: 'SOMBRE',
  AUTO: 'AUTO',
};

const PLATEFORME_VISIO = {
  JITSI: 'JITSI',
  MEET: 'MEET',
};

const STATUT_TELECONSULT = {
  PLANIFIEE: 'PLANIFIEE',
  EN_COURS: 'EN_COURS',
  TERMINEE: 'TERMINEE',
  ANNULEE: 'ANNULEE',
};

const STATUT_ORDONNANCE = {
  ACTIVE: 'ACTIVE',
  DELIVREE: 'DELIVREE',
  EXPIREE: 'EXPIREE',
};

const TYPE_ASSURANCE = {
  CMU: 'CMU',
  CNSS: 'CNSS',
  IPM: 'IPM',
  PRIVEE: 'PRIVEE',
};

module.exports = {
  ROLES,
  STATUT_RDV,
  TYPE_RDV,
  STATUT_PASSAGE,
  NIVEAU_URGENCE,
  STATUT_LIT,
  TYPE_CHAMBRE,
  STATUT_HOSPITALISATION,
  MODE_PAIEMENT,
  OPERATEUR_MOBILE,
  STATUT_TRANSACTION,
  STATUT_PAIEMENT,
  STATUT_NOTIFICATION,
  CANAL_NOTIFICATION,
  LANGUE,
  THEME,
  PLATEFORME_VISIO,
  STATUT_TELECONSULT,
  STATUT_ORDONNANCE,
  TYPE_ASSURANCE,
};
